fixed according to Prospector
robvanderleek/cicd-buzz pull request #6
Opened 2019-02-08 11:55 UTC by VladyslavHnatchenko

Hello @robvanderleek!

Thank you very much, for your article(https://medium.com/bettercode/how-to-build-a-modern-ci-cd-pipeline-5faa01891a5b)!
I corrected the files a bit according to Prospector tool (https://prospector.readthedocs.io/en/master/#). 

Please check.
Thank you.

2019-02-11 15:24 UTC, robvanderleek requested changes
Hi Vladyslav,

Thanks for your PR! 
I try to keep the names of unit-test functions as descriptive as possible, so I don't need comments explaining their intent.

Can you have a look? Apart from that the other changes are nice improvements!
Rob

2019-02-11 15:24 UTC, robvanderleek commented on tests/test_generator.py
> +    """Test simple word."""
Please remove the comment (and optionally rename the test function)

2019-02-11 15:24 UTC, robvanderleek commented on tests/test_generator.py
> +    """Test multiple words."""
Please remove the comment (and optionally rename the test function)

2019-02-11 15:24 UTC, robvanderleek commented on tests/test_generator.py
> +    """Test phrase with at least 5 words."""
Please remove the comment (and optionally rename the test function)

2019-02-12 05:10 UTC, VladyslavHnatchenko commented
Hi Rob,
I deleted comments.
Thanks and have a nice day!

2019-02-12 16:08 UTC, robvanderleek approved these changes

2019-02-12 16:08 UTC, merged